Refactor testing for valid shopts
Instead of testing against a version lookup, we can just try setting
the shopt directly and handling the failure ourselves. It's a little
more brute-force but it's also a little bit less dependent on internal
Bash variables.

The nature of shopts means we can't directly test them without
overriding so much code that we're essentially using a function to
exercise a test (not the other way around). But there's ample comments
describing the important details, like "no major platform ships bash
3 except macOS".

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -6,9 +6,9 @@ fail() {
   exit 1
 }
 
-# checks if a corresponding buildkite variable is set,
-# and then if the shell is new enough to support that
-# particular shopt.
+# checks if a buildkite variable corresponding to a given shopt is set,
+# and then attempts to set it. Errors will be caught and pushed up through
+# error logging along with a note about the required Bash version number.
 set_shopt() {
   local option="${1}"
 
@@ -22,25 +22,31 @@ set_shopt() {
   local value
   value="$(tr '[:upper:]' '[:lower:]' <<< "${!varname:-false}")"
 
-  if [[ ${value} =~ ^(true|1)$ ]]; then
-    bash_version_check "${option}"
-    shopt -s "${option}"
+  # return immediately (and successfully) unless the value is explicitly set to true
+  [[ ${value} =~ ^(true|1)$ ]] || return 0
+
+  # macOS is the last major platform still using Bash 3, and `shopt -q` is
+  # broken on macOS. So we have to mute `shopt` the old-fashioned way
+  # and redirect output to /dev/null. Since the list of options's we'll attempt
+  # to set is so constrained, we can use a small helper fuction to look up
+  # which version of bash introduced a given the shopts in our error handling.
+  if ! shopt -s "${option}" &> /dev/null; then
+    fail "failed to set shopt '${option}: $(bash_version_lookup "${option}")"
   fi
 }
 
-bash_version_check() {
+# look up which version of bash introduced
+# a given shopt and print it to stdout.
+bash_version_lookup() {
   local option="${1}"
   local required
 
   case "${option}" in
     globstar) required="4" ;;
-    extglob) required="3" ;;
-    *)  fail "attempted to set unknown shopt '${option}'" ;;
+    extglob) required="2" ;;
   esac
 
-  if [[ ${BASH_VERSINFO[0]} -lt ${required} ]]; then
-    fail "shopt '${option}' requires Bash ${required} or newer"
-  fi
+  echo "shopt '${option}' requires Bash ${required} or newer"
 }
 
 # Reads either a value or a list from plugin config
